server:
  port: 8083

logging:
  level:
    org.springframework.kafka.transaction: TRACE #related to Kafka Transaction
    org.springframework.transaction: TRACE #for all Transaction based classes in Spring @Application-Context
    org.apache.kafka.clients.producer.internals.TransactionManager: TRACE #to look apache kafka internal transaction manager activity
    org.springframework.kafka.transaction.KafkaTransactionManager: TRACE

spring:
  application:
    name: product-microservice
  profiles:
    active: development
  kafka:
    producer:
      transaction-id-prefix: product-service-${random.value}- #should be different for all pods on cluster! pods, it means consumers.
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5 # can send 5 messages at the same time (means in the same kafka connection for request), will not wait for response, in the Exception time order can be different when retry to write message to the topic. For deepest consistency 1 is Ok.
                  #Kafka documentation says: in-flight-requests-per-connection can not be greater than 5 ! if you try to write value that greater than 5, it'll throw configuration exception, Idempotence is activated! and cannot work with greater than 5 per connection!
                  #to use idempotent producer, it must be at most 5 !
        delivery:
          timeout:
            ms: 120000 # 2min, it means waiting for: send request and retry times (both of them)
        linger:
          ms: 0 # how much time that will wait for batching, 0 means don't wait for message, don't batch
        request:
          timeout:
            ms: 30000 # only waiting for send request time
#      retries: 10
#      properties:
#        retry:
#          backoff:
#            ms: 1000

