server:
  port: 8084

spring:
  application:
    name: email-notification-microservice
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: product-created-events
      properties:
        spring:
          json:
            trusted:
              packages: com.rouvsen.emailnotification.ms.emailnotificationmicroservice.model

  datasource:
    username: rouvsen
    password: rouvsen
    url: jdbc:h2:mem:test_db
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
